name: ansible-playbook
descripot: Run an Ansible playbook
inputs:
  playbook:
    description: The playbook file to run.
    required: true
  requirements:
    description: The path of the requirements.yml file.
    required: false
run:
  using: docker
  image: Dockerfile
  args:
    playbook: ${{ inputs.playbook }}
    requirements: ${{ inputs.requirements }}
