name: ansible-playbook
description: Run an Ansible playbook
inputs:
  playbook:
    description: The playbook file to run.
    required: true
  requirements:
    description: The path of the requirements.yml file.
    required: false
run:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.playbook }}
    - ${{ inputs.requirements }}
