---
- name: Deploy to AWS
  hosts: localhost
  vars:
    domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
  tasks:
    - name: Ensure bucket | static S3
      s3_bucket:
        name: "{{ domain_name }}-static"
        public_access:
          block_public_acls: yes
          block_public_policy: yes
          ignore_public_acls: yes
          restrict_public_buckets: yes
        tags:
          Environment: Production
        state: present
    - name: Sync objects | static S3
      s3_sync:
        bucket: "{{ domain_name }}-static"
        file_change_strategy: checksum
        file_root: ../dist
